x-database-password: &database-password ${DATABASE_PASSWORD:-password}
x-database-port: &database-port ${DATABASE_PORT:-5432}
x-database-user: &database-user ${DATABASE_USER:-postgres}
x-redis-password: &redis-password ${REDIS_PASSWORD:-password}
x-redis-port: &redis-port ${REDIS_PORT:-6379}

name: hanami-db-provider-example

services:
  postgres:
    container_name: hanami-db-provider-example-postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      PGPORT: *database-port
      POSTGRES_PASSWORD: *database-password
      POSTGRES_USER: *database-user
    healthcheck:
      interval: 10s
      retries: 5
      test: sh -c "pg_isready -U $$POSTGRES_USER -p $$PGPORT"
      timeout: 5s
    image: postgres:17
    ports:
      - mode: host
        protocol: tcp
        published: *database-port
        target: *database-port
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    name: test-postgres-data
